In [2]:
from google.colab import auth
auth.authenticate_user()

!git config --global user.email "rabbit082525@gmail.com"
!git config --global user.name "rs-next"

from getpass import getpass
token = getpass('Enter your GitHub token: ')
!git clone https://{token}@github.com/rs-next/AI-Study.git


Enter your GitHub token: ··········
Cloning into 'AI-Study'...


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Activation, Dropout
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelBinarizer
from keras.utils import to_categorical
from imutils import paths
from sklearn.model_selection import train_test_split

In [ ]:
dir_path = '/content/drive/MyDrive/dataset_large'
categories = ['airplane','truck','cat']
data = []

for i in categories:

    paths = os.path.join(dir_path,i)
    print('paths',paths)
    ii=0
    for j in os.listdir(paths):
        img_path = os.path.join(paths,j)
        labels = categories.index(i)

        if (os.path.splitext(img_path)[1]=='.jpg'):
          img = cv2.imread(img_path)
          img = cv2.resize(img,(32,32))
          data.append([img,labels])


random.shuffle(data)
print(len(data))

paths /content/drive/MyDrive/dataset_large/airplane
paths /content/drive/MyDrive/dataset_large/truck
paths /content/drive/MyDrive/dataset_large/cat
600


In [ ]:
x = []
y = []

for features,label in data:
    x.append(features)
    y.append(label)

#Converting lists into numpy arrays
x = np.array(x)
y = np.array(y)
x = x/255.0
x = np.array(x).reshape(-1, 32, 32, 3)
print("Shape of train images is:", x.shape)
print("Shape of labels is:", y.shape)
print(y)
print(x.shape[1:])

Shape of train images is: (600, 32, 32, 3)
Shape of labels is: (600,)
[1 0 0 0 0 1 2 0 1 0 2 0 0 0 1 2 2 2 0 0 0 1 0 2 0 2 0 0 2 0 1 2 1 0 1 0 0
 0 1 0 2 1 2 2 2 2 0 0 2 1 1 1 0 1 2 2 1 2 1 2 2 2 1 0 0 2 1 1 1 1 0 0 2 1
 1 0 2 1 1 0 0 0 2 2 0 1 2 0 0 2 1 1 0 1 2 2 2 1 0 1 1 0 0 0 2 2 2 1 0 0 1
 1 2 1 0 0 1 2 0 0 1 1 1 1 1 2 1 1 0 0 2 0 1 2 1 2 1 1 1 0 0 1 0 0 0 2 2 1
 0 1 1 0 2 2 1 0 1 2 2 2 1 1 1 0 2 0 2 2 2 2 0 2 2 2 0 2 1 1 0 2 1 0 0 1 2
 1 0 2 0 0 1 0 2 1 1 0 0 2 2 1 1 2 0 0 2 0 1 2 0 0 0 2 0 1 0 2 0 1 0 2 2 0
 1 1 1 0 1 0 2 0 1 2 1 0 2 1 1 0 1 2 1 2 2 0 1 1 0 2 0 2 2 0 0 0 2 0 2 2 2
 2 0 2 2 2 1 1 2 0 0 1 0 0 2 2 0 0 2 1 0 0 1 2 1 0 1 1 0 0 2 1 2 2 1 2 1 2
 2 1 2 2 1 2 2 1 1 1 1 2 1 0 1 1 1 0 2 1 0 0 1 0 2 2 1 2 2 0 0 1 2 2 0 1 1
 2 1 0 1 0 2 2 1 0 0 1 2 2 1 1 1 2 0 0 2 0 1 2 0 1 1 1 1 0 1 1 2 1 0 0 0 0
 0 0 0 2 0 0 1 2 1 0 0 1 1 0 2 2 2 1 1 0 1 1 2 0 1 1 2 0 1 1 0 1 2 2 1 2 2
 2 2 2 2 1 0 1 0 1 2 0 2 1 1 0 2 1 1 2 1 0 1 2 2 1 2 1 2 2 0 2 2 1 0 1 1 2
 0 2 2 2 0 1 1 1 0 0 2 2 1 2 2

In [ ]:
model = Sequential()
model.add(Conv2D(32,(4,4), activation='relu', padding='same',input_shape = (x.shape[1:])))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(2,2), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(128,(3,3), activation='relu',padding='same'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))
model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3,activation='softmax'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_14 (Conv2D)          (None, 32, 32, 32)        1568      
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 16, 16, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_15 (Conv2D)          (None, 15, 15, 64)        8256      
                                                                 
 max_pooling2d_14 (MaxPooli  (None, 7, 7, 64)          0         
 ng2D)                                                           
                                                                 
 conv2d_16 (Conv2D)          (None, 5, 5, 64)          36928     
                                                                 
 max_pooling2d_15 (MaxPooli  (None, 2, 2, 64)         

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x, y, epochs=50,batch_size=10,validation_split=0.2)

Epoch 1/50
48/48 [==============================] - 2s 23ms/step - loss: 1.1064 - accuracy: 0.3208 - val_loss: 1.0965 - val_accuracy: 0.3417
Epoch 2/50
48/48 [==============================] - 1s 17ms/step - loss: 1.0948 - accuracy: 0.3604 - val_loss: 1.0964 - val_accuracy: 0.3750
Epoch 3/50
48/48 [==============================] - 1s 17ms/step - loss: 1.0967 - accuracy: 0.3521 - val_loss: 1.0676 - val_accuracy: 0.6000
Epoch 4/50
48/48 [==============================] - 1s 28ms/step - loss: 1.0627 - accuracy: 0.4437 - val_loss: 1.0339 - val_accuracy: 0.5083
Epoch 5/50
48/48 [==============================] - 1s 28ms/step - loss: 1.0492 - accuracy: 0.4750 - val_loss: 0.9417 - val_accuracy: 0.5000
Epoch 6/50
48/48 [==============================] - 1s 29ms/step - loss: 0.9937 - accuracy: 0.5396 - val_loss: 1.0520 - val_accuracy: 0.4250
Epoch 7/50
48/48 [==============================] - 1s 29ms/step - loss: 0.9244 - accuracy: 0.6167 - val_loss: 0.8637 - val_accuracy: 0.6583
Epoch 8/50
48

In [ ]:

import numpy as np


def image(path):
    print('path',path)
    img = cv2.imread(path)

    new_arr = cv2.resize(img, (32, 32))
    new_arr = np.array(new_arr)
    new_arr = new_arr/255.0
    new_arr = new_arr.reshape(-1, 32, 32, 3)

    return new_arr



In [ ]:
dir_path = '/content/drive/MyDrive/dataset_large'
categories = ['test_airplane','test_truck','test_cat']
data = []

correct_cnt=0
for i in categories:

    paths = os.path.join(dir_path,i)
    ii=0
    for j in os.listdir(paths):
        img_path = os.path.join(paths,j)
      #  print(img_path)
        labels = categories.index(i)
      #  print(img_path,labels)
        prediction = model.predict(image(img_path))
        print('labels' ,labels)
        print(np.round(prediction,3))
        print('classification results' ,prediction.argmax())
        if (labels==prediction.argmax()):
            correct_cnt=correct_cnt+1
print('### correnct cnt out of 30==>',correct_cnt)

path /content/drive/MyDrive/dataset_large/test_airplane/0991.jpg
1/1 [==============================] - 0s 155ms/step
labels 0
[[0.999 0.001 0.   ]]
classification results 0
path /content/drive/MyDrive/dataset_large/test_airplane/0995.jpg
1/1 [==============================] - 0s 28ms/step
labels 0
[[0.957 0.01  0.033]]
classification results 0
path /content/drive/MyDrive/dataset_large/test_airplane/0998.jpg
1/1 [==============================] - 0s 33ms/step
labels 0
[[0.549 0.432 0.02 ]]
classification results 0
path /content/drive/MyDrive/dataset_large/test_airplane/0996.jpg
1/1 [==============================] - 0s 28ms/step
labels 0
[[0.978 0.    0.022]]
classification results 0
path /content/drive/MyDrive/dataset_large/test_airplane/0997.jpg
1/1 [==============================] - 0s 32ms/step
labels 0
[[0.163 0.15  0.686]]
classification results 2
path /content/drive/MyDrive/dataset_large/test_airplane/0999.jpg
1/1 [==============================] - 0s 36ms/step
labels 0
[[0.999 

In [ ]:
prediction = model.predict(image('/content/drive/MyDrive/dataset_large/test_cat/0999.jpg'))
#print(prediction.argmax())
print(np.round(prediction,3))
#airplane: 1 0 0, truck : 0 1 0,cat: 0 0 1

path /content/drive/MyDrive/dataset_large/test_cat/0999.jpg
1/1 [==============================] - 0s 29ms/step
[[0. 0. 1.]]
